/* Generated By:JavaCC: Do not edit this line. FLParserTokenManager.java */
package ar.uba.dc.formalex.parser;
import java.util.*;
import ar.uba.dc.formalex.fl.FLInput;
import ar.uba.dc.formalex.fl.bgtheory.*;
import ar.uba.dc.formalex.fl.bgtheory.Timer;
                                             //necesario para desambiguar
import ar.uba.dc.formalex.fl.regulation.formula.terminals.*;
import ar.uba.dc.formalex.fl.regulation.permission.Permission;
import ar.uba.dc.formalex.fl.regulation.rules.*;
import ar.uba.dc.formalex.fl.regulation.formula.connectors.*;
import ar.uba.dc.formalex.fl.regulation.formula.FLFormula;

/** Token Manager. */
public class FLParserTokenManager implements FLParserConstants
{

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0, long active1)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x40000000000000L) != 0L || (active1 & 0x2000L) != 0L)
            return 6;
         if ((active0 & 0xf70003ffffffff00L) != 0L || (active1 & 0x7L) != 0L)
         {
            jjmatchedKind = 75;
            return 4;
         }
         return -1;
      case 1:
         if ((active0 & 0x100000000L) != 0L)
            return 4;
         if ((active0 & 0xf00003feffffff00L) != 0L || (active1 & 0x7L) != 0L)
         {
            jjmatchedKind = 75;
            jjmatchedPos = 1;
            return 4;
         }
         return -1;
      case 2:
         if ((active0 & 0x8000001000000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x700003eeffffff00L) != 0L || (active1 & 0x7L) != 0L)
         {
            jjmatchedKind = 75;
            jjmatchedPos = 2;
            return 4;
         }
         return -1;
      case 3:
         if ((active0 & 0xc000000000L) != 0L)
         {
            if (jjmatchedPos < 2)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 2;
            }
            return -1;
         }
         if ((active0 & 0x8000001000000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x7000032efbffff00L) != 0L || (active1 & 0x7L) != 0L)
         {
            jjmatchedKind = 75;
            jjmatchedPos = 3;
            return 4;
         }
         return -1;
      case 4:
         if ((active0 & 0x70000306fba6f700L) != 0L || (active1 & 0x7L) != 0L)
         {
            jjmatchedKind = 75;
            jjmatchedPos = 4;
            return 4;
         }
         if ((active0 & 0x500800L) != 0L)
            return 4;
         if ((active0 & 0xc000000000L) != 0L)
         {
            if (jjmatchedPos < 2)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 2;
            }
            return -1;
         }
         if ((active0 & 0x8000001000000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x2800090000L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 3;
            }
            return -1;
         }
         return -1;
      case 5:
         if ((active0 & 0x70000306eaa6e400L) != 0L || (active1 & 0x6L) != 0L)
         {
            if (jjmatchedPos != 5)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 5;
            }
            return 4;
         }
         if ((active0 & 0x300L) != 0L || (active1 & 0x1L) != 0L)
            return 4;
         if ((active0 & 0x11001000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active0 & 0xc000000000L) != 0L)
         {
            if (jjmatchedPos < 2)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 2;
            }
            return -1;
         }
         if ((active0 & 0x8000001000000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x2800090000L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 3;
            }
            return -1;
         }
         return -1;
      case 6:
         if ((active0 & 0x70000302caa2c400L) != 0L)
         {
            jjmatchedKind = 75;
            jjmatchedPos = 6;
            return 4;
         }
         if ((active0 & 0x200L) != 0L)
            return 4;
         if ((active0 & 0x420042000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active0 & 0x11001000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active0 & 0xc000000000L) != 0L)
         {
            if (jjmatchedPos < 2)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 2;
            }
            return -1;
         }
         if ((active0 & 0x8000001000000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x2800090000L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 3;
            }
            return -1;
         }
         return -1;
      case 7:
         if ((active0 & 0x40000302ca820400L) != 0L)
         {
            jjmatchedKind = 75;
            jjmatchedPos = 7;
            return 4;
         }
         if ((active0 & 0x1000000000204000L) != 0L)
            return 4;
         if ((active0 & 0x2000000000008000L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0x420042000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active0 & 0x11001000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active0 & 0xc000000000L) != 0L)
         {
            if (jjmatchedPos < 2)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 2;
            }
            return -1;
         }
         if ((active0 & 0x8000001000000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x2800090000L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 3;
            }
            return -1;
         }
         return -1;
      case 8:
         if ((active0 & 0xc8820400L) != 0L)
         {
            jjmatchedKind = 75;
            jjmatchedPos = 8;
            return 4;
         }
         if ((active0 & 0x4000030202000000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 7;
            }
            return -1;
         }
         if ((active0 & 0x2000000000008000L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0x420042000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active0 & 0x11001000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active0 & 0x8000000000000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0xc000000000L) != 0L)
         {
            if (jjmatchedPos < 2)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 2;
            }
            return -1;
         }
         if ((active0 & 0x2800090000L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 3;
            }
            return -1;
         }
         return -1;
      case 9:
         if ((active0 & 0x820400L) != 0L)
         {
            jjmatchedKind = 75;
            jjmatchedPos = 9;
            return 4;
         }
         if ((active0 & 0xc0000000L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active0 & 0x4000030202000000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 7;
            }
            return -1;
         }
         if ((active0 & 0x2000000000008000L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0x420042000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active0 & 0x11001000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active0 & 0x8000000000000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x2800090000L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 3;
            }
            return -1;
         }
         return -1;
      case 10:
         if ((active0 & 0x420042000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active0 & 0x20000L) != 0L)
            return 4;
         if ((active0 & 0x800000L) != 0L)
         {
            jjmatchedKind = 75;
            jjmatchedPos = 10;
            return 4;
         }
         if ((active0 & 0x11001000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active0 & 0x400L) != 0L)
         {
            if (jjmatchedPos < 9)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 9;
            }
            return -1;
         }
         if ((active0 & 0x800090000L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 3;
            }
            return -1;
         }
         if ((active0 & 0xc0000000L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active0 & 0x4000030202000000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 7;
            }
            return -1;
         }
         if ((active0 & 0x8000000000000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x8000L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 6;
            }
            return -1;
         }
         return -1;
      case 11:
         if ((active0 & 0x420042000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active0 & 0x11001000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active0 & 0x400L) != 0L)
         {
            if (jjmatchedPos < 9)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 9;
            }
            return -1;
         }
         if ((active0 & 0x800000L) != 0L)
         {
            jjmatchedKind = 75;
            jjmatchedPos = 11;
            return 4;
         }
         if ((active0 & 0x800090000L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 3;
            }
            return -1;
         }
         if ((active0 & 0xc0000000L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active0 & 0x30202000000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 7;
            }
            return -1;
         }
         if ((active0 & 0x8000000000000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x8000L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 6;
            }
            return -1;
         }
         return -1;
      case 12:
         if ((active0 & 0x420042000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active0 & 0x11001000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active0 & 0x800000L) != 0L)
         {
            if (jjmatchedPos < 11)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 11;
            }
            return -1;
         }
         if ((active0 & 0x400L) != 0L)
         {
            if (jjmatchedPos < 9)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 9;
            }
            return -1;
         }
         if ((active0 & 0x800090000L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 3;
            }
            return -1;
         }
         if ((active0 & 0xc0000000L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active0 & 0x30202000000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 7;
            }
            return -1;
         }
         if ((active0 & 0x8000000000000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x8000L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 6;
            }
            return -1;
         }
         return -1;
      case 13:
         if ((active0 & 0x420002000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active0 & 0x1001000L) != 0L)
         {
            if (jjmatchedPos < 4)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 4;
            }
            return -1;
         }
         if ((active0 & 0x800000L) != 0L)
         {
            if (jjmatchedPos < 11)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 11;
            }
            return -1;
         }
         if ((active0 & 0x400L) != 0L)
         {
            if (jjmatchedPos < 9)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 9;
            }
            return -1;
         }
         if ((active0 & 0x800090000L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 3;
            }
            return -1;
         }
         if ((active0 & 0xc0000000L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active0 & 0x30002000000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 7;
            }
            return -1;
         }
         if ((active0 & 0x8000000000000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x8000L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 6;
            }
            return -1;
         }
         return -1;
      case 14:
         if ((active0 & 0x400L) != 0L)
         {
            if (jjmatchedPos < 9)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 9;
            }
            return -1;
         }
         if ((active0 & 0xc0000000L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active0 & 0x30002000000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 7;
            }
            return -1;
         }
         if ((active0 & 0x8000L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0x400002000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active0 & 0x8000000000000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x800090000L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 3;
            }
            return -1;
         }
         if ((active0 & 0x800000L) != 0L)
         {
            if (jjmatchedPos < 11)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 11;
            }
            return -1;
         }
         return -1;
      case 15:
         if ((active0 & 0x400L) != 0L)
         {
            if (jjmatchedPos < 9)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 9;
            }
            return -1;
         }
         if ((active0 & 0x400000000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active0 & 0xc0000000L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active0 & 0x30002000000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 7;
            }
            return -1;
         }
         if ((active0 & 0x8000L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0x800090000L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 3;
            }
            return -1;
         }
         if ((active0 & 0x800000L) != 0L)
         {
            if (jjmatchedPos < 11)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 11;
            }
            return -1;
         }
         return -1;
      case 16:
         if ((active0 & 0x400L) != 0L)
         {
            if (jjmatchedPos < 9)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 9;
            }
            return -1;
         }
         if ((active0 & 0x400000000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active0 & 0xc0000000L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active0 & 0x30002000000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 7;
            }
            return -1;
         }
         if ((active0 & 0x8000L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0x90000L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 3;
            }
            return -1;
         }
         if ((active0 & 0x800000L) != 0L)
         {
            if (jjmatchedPos < 11)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 11;
            }
            return -1;
         }
         return -1;
      case 17:
         if ((active0 & 0x30000000000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 7;
            }
            return -1;
         }
         if ((active0 & 0x400000000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active0 & 0xc0000000L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active0 & 0x8000L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0x90000L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 3;
            }
            return -1;
         }
         return -1;
      case 18:
         if ((active0 & 0x30000000000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 7;
            }
            return -1;
         }
         if ((active0 & 0xc0000000L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active0 & 0x90000L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 3;
            }
            return -1;
         }
         return -1;
      case 19:
         if ((active0 & 0x30000000000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 7;
            }
            return -1;
         }
         if ((active0 & 0xc0000000L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active0 & 0x10000L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 3;
            }
            return -1;
         }
         return -1;
      case 20:
         if ((active0 & 0x30000000000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 7;
            }
            return -1;
         }
         if ((active0 & 0xc0000000L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 8;
            }
            return -1;
         }
         return -1;
      case 21:
         if ((active0 & 0x30000000000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 7;
            }
            return -1;
         }
         return -1;
      case 22:
         if ((active0 & 0x30000000000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 7;
            }
            return -1;
         }
         return -1;
      case 23:
         if ((active0 & 0x30000000000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 7;
            }
            return -1;
         }
         return -1;
      case 24:
         if ((active0 & 0x30000000000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 7;
            }
            return -1;
         }
         return -1;
      case 25:
         if ((active0 & 0x30000000000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 7;
            }
            return -1;
         }
         return -1;
      case 26:
         if ((active0 & 0x30000000000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 75;
               jjmatchedPos = 7;
            }
            return -1;
         }
         return -1;
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0, long active1)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 33:
         return jjStopAtPos(0, 55);
      case 35:
         return jjMoveStringLiteralDfa1_0(0xc0L, 0x0L);
      case 37:
         return jjStopAtPos(0, 72);
      case 38:
         return jjStopAtPos(0, 52);
      case 40:
         return jjStopAtPos(0, 42);
      case 41:
         return jjStopAtPos(0, 43);
      case 44:
         jjmatchedKind = 59;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x40000L);
      case 45:
         jjmatchedKind = 77;
         return jjMoveStringLiteralDfa1_0(0x40000000000000L, 0x0L);
      case 46:
         return jjStopAtPos(0, 48);
      case 58:
         return jjStopAtPos(0, 49);
      case 59:
         return jjStopAtPos(0, 83);
      case 60:
         jjmatchedKind = 68;
         return jjMoveStringLiteralDfa1_0(0x4000000000000L, 0x40L);
      case 61:
         return jjStopAtPos(0, 67);
      case 62:
         jjmatchedKind = 69;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x80L);
      case 91:
         jjmatchedKind = 46;
         return jjMoveStringLiteralDfa1_0(0x8000000000000L, 0x0L);
      case 93:
         return jjStopAtPos(0, 47);
      case 95:
         return jjStopAtPos(0, 78);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa1_0(0x1000300L, 0x0L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa1_0(0x108000000L, 0x0L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa1_0(0x400000L, 0x0L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa1_0(0x82208000L, 0x0L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x2L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa1_0(0x200000000000000L, 0x4L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa1_0(0x20002000L, 0x0L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa1_0(0x8000002040004400L, 0x1L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa1_0(0x10001000L, 0x0L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa1_0(0xc000000000L, 0x0L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa1_0(0x11000000000f0000L, 0x0L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa1_0(0x400000200000000L, 0x0L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa1_0(0x6000030400100000L, 0x0L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa1_0(0x800800000L, 0x0L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa1_0(0x1004000800L, 0x0L);
      case 123:
         return jjStopAtPos(0, 44);
      case 124:
         return jjStopAtPos(0, 53);
      case 125:
         return jjStopAtPos(0, 45);
      default :
         return jjMoveNfa_0(2, 0);
   }
}
static private int jjMoveStringLiteralDfa1_0(long active0, long active1)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1);
      return 1;
   }
   switch(curChar)
   {
      case 32:
         if ((active1 & 0x40000L) != 0L)
            return jjStopAtPos(1, 82);
         break;
      case 40:
         if ((active0 & 0x100000000000000L) != 0L)
            return jjStopAtPos(1, 56);
         else if ((active0 & 0x200000000000000L) != 0L)
            return jjStopAtPos(1, 57);
         else if ((active0 & 0x400000000000000L) != 0L)
            return jjStopAtPos(1, 58);
         break;
      case 61:
         if ((active1 & 0x40L) != 0L)
            return jjStopAtPos(1, 70);
         else if ((active1 & 0x80L) != 0L)
            return jjStopAtPos(1, 71);
         break;
      case 62:
         if ((active0 & 0x4000000000000L) != 0L)
            return jjStopAtPos(1, 50);
         else if ((active0 & 0x40000000000000L) != 0L)
            return jjStopAtPos(1, 54);
         break;
      case 93:
         if ((active0 & 0x8000000000000L) != 0L)
            return jjStopAtPos(1, 51);
         break;
      case 65:
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x8004000000L, active1, 0L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa2_0(active0, 0x40L, active1, 0L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000000020380L, active1, 0L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x6000030c88008000L, active1, 0L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x4002200800L, active1, 0L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x21002000L, active1, 0L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa2_0(active0, 0x400L, active1, 0L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x2040094000L, active1, 0x1L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x1010501000L, active1, 0x4L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x200000000L, active1, 0L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000000000000000L, active1, 0L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000L, active1, 0L);
      case 88:
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x2L);
      case 89:
      case 121:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(1, 32, 4);
         return jjMoveStringLiteralDfa2_0(active0, 0x800000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1);
}
static private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(0, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1);
      return 2;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000001000000000L, active1, 0L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x30000000040L, active1, 0L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000d0021000L, active1, 0L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0xc000L, active1, 0L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000L, active1, 0L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000000L, active1, 0x2L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x9190080L, active1, 0L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0x800L, active1, 0L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000800000L, active1, 0L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x220002000L, active1, 0L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000000000400L, active1, 0L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x4L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000402200000L, active1, 0x1L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa3_0(active0, 0x800040300L, active1, 0L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa3_0(active0, 0x400000L, active1, 0L);
      case 88:
      case 120:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1);
}
static private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(1, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, active1);
      return 3;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa4_0(active0, 0xc000000000L, active1, 0L);
      case 58:
         if ((active0 & 0x4000000L) != 0L)
            return jjStopAtPos(3, 26);
         break;
      case 65:
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000012001080L, active1, 0x4L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa4_0(active0, 0x20002000L, active1, 0L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x30000800040L, active1, 0L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000400500c00L, active1, 0L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0xc300L, active1, 0x1L);
      case 74:
      case 106:
         return jjMoveStringLiteralDfa4_0(active0, 0x200000L, active1, 0L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0x9000000L, active1, 0L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa4_0(active0, 0x40000L, active1, 0L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa4_0(active0, 0xc0000000L, active1, 0L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x800000000L, active1, 0x2L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000000L, active1, 0L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x3000000000020000L, active1, 0L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa4_0(active0, 0x1200000000L, active1, 0L);
      case 89:
      case 121:
         return jjMoveStringLiteralDfa4_0(active0, 0x90000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, active1);
}
static private int jjMoveStringLiteralDfa4_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(2, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, active1);
      return 4;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa5_0(active0, 0x2800090000L, active1, 0L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x1020002000L, active1, 0L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x1L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa5_0(active0, 0xc0000000L, active1, 0L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa5_0(active0, 0x30000800000L, active1, 0L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000200000000L, active1, 0L);
      case 75:
      case 107:
         return jjMoveStringLiteralDfa5_0(active0, 0x40L, active1, 0L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000012001000L, active1, 0x4L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0x800c000L, active1, 0L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x200300L, active1, 0L);
      case 82:
      case 114:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(4, 11, 4);
         else if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(4, 22, 4);
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000000020400L, active1, 0L);
      case 83:
      case 115:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(4, 20, 4);
         break;
      case 84:
      case 116:
         return jjMoveStringLiteralDfa5_0(active0, 0x400000000L, active1, 0x2L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x40080L, active1, 0L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa5_0(active0, 0xc000000000L, active1, 0L);
      case 87:
      case 119:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000L, active1, 0L);
      case 88:
      case 120:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0, active1);
}
static private int jjMoveStringLiteralDfa5_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(3, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, active1);
      return 5;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa6_0(active0, 0x11001000L, active1, 0L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0xc0c0000000L, active1, 0L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa6_0(active0, 0x8000000000000000L, active1, 0L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa6_0(active0, 0x200000000L, active1, 0L);
      case 69:
      case 101:
         if ((active1 & 0x1L) != 0L)
            return jjStartNfaWithStates_0(5, 64, 4);
         return jjMoveStringLiteralDfa6_0(active0, 0x8000L, active1, 0L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa6_0(active0, 0x8000040L, active1, 0L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x30000204000L, active1, 0L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa6_0(active0, 0x1022002000L, active1, 0x4L);
      case 78:
      case 110:
         if ((active0 & 0x100L) != 0L)
         {
            jjmatchedKind = 8;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x200L, active1, 0L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa6_0(active0, 0x10000L, active1, 0L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa6_0(active0, 0x80000L, active1, 0L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa6_0(active0, 0x5000000000820000L, active1, 0L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa6_0(active0, 0x400000480L, active1, 0x2L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa6_0(active0, 0x2000000000040000L, active1, 0L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa6_0(active0, 0x2000000000L, active1, 0L);
      case 87:
      case 119:
         return jjMoveStringLiteralDfa6_0(active0, 0x800000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0, active1);
}
static private int jjMoveStringLiteralDfa6_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(4, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, active1);
      return 6;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa7_0(active0, 0x420042000L, active1, 0L);
      case 40:
         if ((active1 & 0x2L) != 0L)
            return jjStopAtPos(6, 65);
         else if ((active1 & 0x4L) != 0L)
            return jjStopAtPos(6, 66);
         break;
      case 65:
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x2001000000L, active1, 0L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0x10010000L, active1, 0L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa7_0(active0, 0x8000L, active1, 0L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa7_0(active0, 0xd0000002000a0080L, active1, 0L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0x800001000L, active1, 0L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa7_0(active0, 0xc000000000L, active1, 0L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa7_0(active0, 0x30000200000L, active1, 0L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0x2800400L, active1, 0L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa7_0(active0, 0x40L, active1, 0L);
      case 83:
      case 115:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(6, 9, 4);
         return jjMoveStringLiteralDfa7_0(active0, 0x20000000c8000000L, active1, 0L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa7_0(active0, 0x4000L, active1, 0L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0, active1);
}
static private int jjMoveStringLiteralDfa7_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(5, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, 0L);
      return 7;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa8_0(active0, 0x2000000000008000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa8_0(active0, 0x20010000L);
      case 68:
      case 100:
         if ((active0 & 0x1000000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 60, 4);
         return jjMoveStringLiteralDfa8_0(active0, 0x4000000200000000L);
      case 69:
      case 101:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(7, 14, 4);
         else if ((active0 & 0x1000000000L) != 0L)
            return jjStopAtPos(7, 36);
         return jjMoveStringLiteralDfa8_0(active0, 0xc0000000L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa8_0(active0, 0x30000000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa8_0(active0, 0x2000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa8_0(active0, 0x2000000000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa8_0(active0, 0x821400L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa8_0(active0, 0x10000040L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa8_0(active0, 0x8000000000000000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa8_0(active0, 0x80000L);
      case 83:
      case 115:
         if ((active0 & 0x80L) != 0L)
            return jjStopAtPos(7, 7);
         break;
      case 84:
      case 116:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(7, 21, 4);
         return jjMoveStringLiteralDfa8_0(active0, 0x808000000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa8_0(active0, 0xc001000000L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa8_0(active0, 0x40000L);
      case 87:
      case 119:
         return jjMoveStringLiteralDfa8_0(active0, 0x402000000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0, 0L);
}
static private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, 0L);
      return 8;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa9_0(active0, 0x4000030202000000L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa9_0(active0, 0x40400L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa9_0(active0, 0x8000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa9_0(active0, 0x20000L);
      case 69:
      case 101:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStopAtPos(8, 38);
         else if ((active0 & 0x8000000000L) != 0L)
            return jjStopAtPos(8, 39);
         break;
      case 70:
      case 102:
         return jjMoveStringLiteralDfa9_0(active0, 0x80000L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa9_0(active0, 0x800000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa9_0(active0, 0x2000000400800000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa9_0(active0, 0x2000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa9_0(active0, 0x28000000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa9_0(active0, 0xc0000000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa9_0(active0, 0x8000000001001000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa9_0(active0, 0x2010010040L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0, 0L);
}
static private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0, 0L);
      return 9;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa10_0(active0, 0x8c0000000L);
      case 58:
         if ((active0 & 0x8000000L) != 0L)
            return jjStopAtPos(9, 27);
         break;
      case 65:
      case 97:
         return jjMoveStringLiteralDfa10_0(active0, 0x2000000L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa10_0(active0, 0x4000000000000000L);
      case 69:
      case 101:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStopAtPos(9, 37);
         return jjMoveStringLiteralDfa10_0(active0, 0x21000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa10_0(active0, 0x8000000000000000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa10_0(active0, 0x40400L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa10_0(active0, 0x30000000000L);
      case 78:
      case 110:
         if ((active0 & 0x2000000000000000L) != 0L)
            return jjStopAtPos(9, 61);
         return jjMoveStringLiteralDfa10_0(active0, 0x10000040L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa10_0(active0, 0x1080000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa10_0(active0, 0x10000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa10_0(active0, 0x600002000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa10_0(active0, 0x20000000L);
      case 89:
      case 121:
         return jjMoveStringLiteralDfa10_0(active0, 0x8000L);
      case 90:
      case 122:
         return jjMoveStringLiteralDfa10_0(active0, 0x800000L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0, 0L);
}
static private int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0, 0L);
      return 10;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa11_0(active0, 0x8400L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa11_0(active0, 0x20800000000L);
      case 68:
      case 100:
         if ((active0 & 0x40L) != 0L)
            return jjStopAtPos(10, 6);
         break;
      case 69:
      case 101:
         return jjMoveStringLiteralDfa11_0(active0, 0x802000L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa11_0(active0, 0x600000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa11_0(active0, 0x10000000000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa11_0(active0, 0x20000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa11_0(active0, 0x8000000000000000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa11_0(active0, 0x81000L);
      case 83:
      case 115:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(10, 17, 4);
         return jjMoveStringLiteralDfa11_0(active0, 0x1010000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa11_0(active0, 0x10000000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa11_0(active0, 0x2040000L);
      case 87:
      case 119:
         return jjMoveStringLiteralDfa11_0(active0, 0xc0000000L);
      case 89:
      case 121:
         if ((active0 & 0x4000000000000000L) != 0L)
            return jjStopAtPos(10, 62);
         break;
      default :
         break;
   }
   return jjStartNfa_0(9, active0, 0L);
}
static private int jjMoveStringLiteralDfa11_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0, 0L);
      return 11;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa12_0(active0, 0x400010000L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa12_0(active0, 0x200008400L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa12_0(active0, 0x800000000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa12_0(active0, 0x10040000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa12_0(active0, 0xc0000000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa12_0(active0, 0x80000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa12_0(active0, 0x8000010000000000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa12_0(active0, 0x2000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa12_0(active0, 0x800000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa12_0(active0, 0x22000000L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa12_0(active0, 0x1000L);
      case 88:
      case 120:
         return jjMoveStringLiteralDfa12_0(active0, 0x20000000000L);
      case 89:
      case 121:
         return jjMoveStringLiteralDfa12_0(active0, 0x1000000L);
      default :
         break;
   }
   return jjStartNfa_0(10, active0, 0L);
}
static private int jjMoveStringLiteralDfa12_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(10, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0, 0L);
      return 12;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa13_0(active0, 0x8000030000800000L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa13_0(active0, 0x400081000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa13_0(active0, 0x8400L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa13_0(active0, 0x20000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa13_0(active0, 0x10000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa13_0(active0, 0x1000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa13_0(active0, 0x2000000L);
      case 82:
      case 114:
         if ((active0 & 0x10000000L) != 0L)
            return jjStopAtPos(12, 28);
         break;
      case 83:
      case 115:
         if ((active0 & 0x40000L) != 0L)
            return jjStopAtPos(12, 18);
         break;
      case 84:
      case 116:
         if ((active0 & 0x200000000L) != 0L)
            return jjStopAtPos(12, 33);
         return jjMoveStringLiteralDfa13_0(active0, 0x8c0000000L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa13_0(active0, 0x2000L);
      default :
         break;
   }
   return jjStartNfa_0(11, active0, 0L);
}
static private int jjMoveStringLiteralDfa13_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(11, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0, 0L);
      return 13;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa14_0(active0, 0x2000L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa14_0(active0, 0x80000L);
      case 67:
      case 99:
         if ((active0 & 0x1000000L) != 0L)
            return jjStopAtPos(13, 24);
         return jjMoveStringLiteralDfa14_0(active0, 0x400000000L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa14_0(active0, 0xc0000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa14_0(active0, 0x30800000000L);
      case 76:
      case 108:
         if ((active0 & 0x1000L) != 0L)
            return jjStopAtPos(13, 12);
         break;
      case 78:
      case 110:
         return jjMoveStringLiteralDfa14_0(active0, 0x10000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa14_0(active0, 0x8000000000000000L);
      case 82:
      case 114:
         if ((active0 & 0x20000000L) != 0L)
            return jjStopAtPos(13, 29);
         break;
      case 83:
      case 115:
         return jjMoveStringLiteralDfa14_0(active0, 0x2000000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa14_0(active0, 0x8400L);
      case 87:
      case 119:
         return jjMoveStringLiteralDfa14_0(active0, 0x800000L);
      default :
         break;
   }
   return jjStartNfa_0(12, active0, 0L);
}
static private int jjMoveStringLiteralDfa14_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(12, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, active0, 0L);
      return 14;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa15_0(active0, 0xc0010000L);
      case 70:
      case 102:
         if ((active0 & 0x8000000000000000L) != 0L)
            return jjStopAtPos(14, 63);
         break;
      case 73:
      case 105:
         return jjMoveStringLiteralDfa15_0(active0, 0x808400L);
      case 76:
      case 108:
         if ((active0 & 0x2000L) != 0L)
            return jjStopAtPos(14, 13);
         return jjMoveStringLiteralDfa15_0(active0, 0x80000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa15_0(active0, 0x30000000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa15_0(active0, 0x800000000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa15_0(active0, 0x400000000L);
      case 89:
      case 121:
         return jjMoveStringLiteralDfa15_0(active0, 0x2000000L);
      default :
         break;
   }
   return jjStartNfa_0(13, active0, 0L);
}
static private int jjMoveStringLiteralDfa15_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(13, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(14, active0, 0L);
      return 15;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa16_0(active0, 0xc0000000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa16_0(active0, 0x80000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa16_0(active0, 0x400000000L);
      case 78:
      case 110:
         if ((active0 & 0x800000000L) != 0L)
            return jjStopAtPos(15, 35);
         return jjMoveStringLiteralDfa16_0(active0, 0x2000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa16_0(active0, 0x8400L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa16_0(active0, 0x30000000000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa16_0(active0, 0x10000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa16_0(active0, 0x800000L);
      default :
         break;
   }
   return jjStartNfa_0(14, active0, 0L);
}
static private int jjMoveStringLiteralDfa16_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(14, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(15, active0, 0L);
      return 16;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa17_0(active0, 0x80000L);
      case 67:
      case 99:
         if ((active0 & 0x2000000L) != 0L)
            return jjStopAtPos(16, 25);
         return jjMoveStringLiteralDfa17_0(active0, 0xc0010000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa17_0(active0, 0x30000000000L);
      case 72:
      case 104:
         if ((active0 & 0x800000L) != 0L)
            return jjStopAtPos(16, 23);
         break;
      case 78:
      case 110:
         if ((active0 & 0x400L) != 0L)
            return jjStopAtPos(16, 10);
         return jjMoveStringLiteralDfa17_0(active0, 0x8000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa17_0(active0, 0x400000000L);
      default :
         break;
   }
   return jjStartNfa_0(15, active0, 0L);
}
static private int jjMoveStringLiteralDfa17_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(15, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(16, active0, 0L);
      return 17;
   }
   switch(curChar)
   {
      case 66:
      case 98:
         return jjMoveStringLiteralDfa18_0(active0, 0x80000L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa18_0(active0, 0x30000000000L);
      case 78:
      case 110:
         if ((active0 & 0x400000000L) != 0L)
            return jjStopAtPos(17, 34);
         break;
      case 79:
      case 111:
         return jjMoveStringLiteralDfa18_0(active0, 0x10000L);
      case 83:
      case 115:
         if ((active0 & 0x8000L) != 0L)
            return jjStopAtPos(17, 15);
         break;
      case 84:
      case 116:
         return jjMoveStringLiteralDfa18_0(active0, 0xc0000000L);
      default :
         break;
   }
   return jjStartNfa_0(16, active0, 0L);
}
static private int jjMoveStringLiteralDfa18_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(16, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(17, active0, 0L);
      return 18;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         return jjMoveStringLiteralDfa19_0(active0, 0x30000000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa19_0(active0, 0xc0000000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa19_0(active0, 0x10000L);
      case 89:
      case 121:
         if ((active0 & 0x80000L) != 0L)
            return jjStopAtPos(18, 19);
         break;
      default :
         break;
   }
   return jjStartNfa_0(17, active0, 0L);
}
static private int jjMoveStringLiteralDfa19_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(17, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(18, active0, 0L);
      return 19;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         if ((active0 & 0x10000L) != 0L)
            return jjStopAtPos(19, 16);
         break;
      case 79:
      case 111:
         return jjMoveStringLiteralDfa20_0(active0, 0xc0000000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa20_0(active0, 0x30000000000L);
      default :
         break;
   }
   return jjStartNfa_0(18, active0, 0L);
}
static private int jjMoveStringLiteralDfa20_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(18, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(19, active0, 0L);
      return 20;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa21_0(active0, 0x30000000000L);
      case 78:
      case 110:
         if ((active0 & 0x40000000L) != 0L)
            return jjStopAtPos(20, 30);
         else if ((active0 & 0x80000000L) != 0L)
            return jjStopAtPos(20, 31);
         break;
      default :
         break;
   }
   return jjStartNfa_0(19, active0, 0L);
}
static private int jjMoveStringLiteralDfa21_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(19, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(20, active0, 0L);
      return 21;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa22_0(active0, 0x30000000000L);
      default :
         break;
   }
   return jjStartNfa_0(20, active0, 0L);
}
static private int jjMoveStringLiteralDfa22_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(20, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(21, active0, 0L);
      return 22;
   }
   switch(curChar)
   {
      case 67:
      case 99:
         return jjMoveStringLiteralDfa23_0(active0, 0x30000000000L);
      default :
         break;
   }
   return jjStartNfa_0(21, active0, 0L);
}
static private int jjMoveStringLiteralDfa23_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(21, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(22, active0, 0L);
      return 23;
   }
   switch(curChar)
   {
      case 84:
      case 116:
         return jjMoveStringLiteralDfa24_0(active0, 0x30000000000L);
      default :
         break;
   }
   return jjStartNfa_0(22, active0, 0L);
}
static private int jjMoveStringLiteralDfa24_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(22, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(23, active0, 0L);
      return 24;
   }
   switch(curChar)
   {
      case 73:
      case 105:
         return jjMoveStringLiteralDfa25_0(active0, 0x30000000000L);
      default :
         break;
   }
   return jjStartNfa_0(23, active0, 0L);
}
static private int jjMoveStringLiteralDfa25_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(23, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(24, active0, 0L);
      return 25;
   }
   switch(curChar)
   {
      case 79:
      case 111:
         return jjMoveStringLiteralDfa26_0(active0, 0x30000000000L);
      default :
         break;
   }
   return jjStartNfa_0(24, active0, 0L);
}
static private int jjMoveStringLiteralDfa26_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(24, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(25, active0, 0L);
      return 26;
   }
   switch(curChar)
   {
      case 78:
      case 110:
         return jjMoveStringLiteralDfa27_0(active0, 0x30000000000L);
      default :
         break;
   }
   return jjStartNfa_0(25, active0, 0L);
}
static private int jjMoveStringLiteralDfa27_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(25, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(26, active0, 0L);
      return 27;
   }
   switch(curChar)
   {
      case 83:
      case 115:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStopAtPos(27, 40);
         else if ((active0 & 0x20000000000L) != 0L)
            return jjStopAtPos(27, 41);
         break;
      default :
         break;
   }
   return jjStartNfa_0(26, active0, 0L);
}
static private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 9;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 2:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 76)
                        kind = 76;
                     jjCheckNAddTwoStates(8, 6);
                  }
                  else if (curChar == 45)
                     jjCheckNAdd(6);
                  else if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 0;
                  break;
               case 0:
                  if (curChar != 47)
                     break;
                  if (kind > 5)
                     kind = 5;
                  jjCheckNAdd(1);
                  break;
               case 1:
                  if ((0xffffffffffffdbffL & l) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  jjCheckNAdd(1);
                  break;
               case 4:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 75)
                     kind = 75;
                  jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 5:
                  if (curChar == 45)
                     jjCheckNAdd(6);
                  break;
               case 6:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 79)
                     kind = 79;
                  jjCheckNAdd(6);
                  break;
               case 7:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 76)
                     kind = 76;
                  jjCheckNAddTwoStates(8, 6);
                  break;
               case 8:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 76)
                     kind = 76;
                  jjCheckNAdd(8);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 2:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 75)
                     kind = 75;
                  jjCheckNAdd(4);
                  break;
               case 1:
                  if (kind > 5)
                     kind = 5;
                  jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 4:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 75)
                     kind = 75;
                  jjCheckNAdd(4);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  jjstateSet[jjnewStateCnt++] = 1;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 9 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
private static final int jjStopStringLiteralDfa_1(int pos, long active0, long active1)
{
   switch (pos)
   {
      default :
         return -1;
   }
}
private static final int jjStartNfa_1(int pos, long active0, long active1)
{
   return jjMoveNfa_1(jjStopStringLiteralDfa_1(pos, active0, active1), pos + 1);
}
static private int jjMoveStringLiteralDfa0_1()
{
   switch(curChar)
   {
      case 37:
         return jjStopAtPos(0, 73);
      default :
         return jjMoveNfa_1(0, 0);
   }
}
static private int jjMoveNfa_1(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 1;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0xffffffdfffffffffL & l) == 0L)
                     break;
                  kind = 74;
                  jjstateSet[jjnewStateCnt++] = 0;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  kind = 74;
                  jjstateSet[jjnewStateCnt++] = 0;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 74)
                     kind = 74;
                  jjstateSet[jjnewStateCnt++] = 0;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 1 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, "\50", "\51", "\173", "\175", "\133", "\135", "\56", "\72", "\74\76", 
"\133\135", "\46", "\174", "\55\76", "\41", null, null, null, "\54", null, null, null, 
null, null, null, null, "\75", "\74", "\76", "\74\75", "\76\75", "\45", "\45", null, 
null, null, "\55", "\137", null, null, null, "\54\40", "\73", };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
   "IN_RAW_TEXT_MODE",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, 0, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0xffffffffffffffc1L, 0xcffffL, 
};
static final long[] jjtoSkip = {
   0x3eL, 0x0L, 
};
static protected SimpleCharStream input_stream;
static private final int[] jjrounds = new int[9];
static private final int[] jjstateSet = new int[18];
private static final StringBuilder jjimage = new StringBuilder();
private static StringBuilder image = jjimage;
private static int jjimageLen;
private static int lengthOfMatch;
static protected char curChar;
/** Constructor. */
public FLParserTokenManager(SimpleCharStream stream){
   if (input_stream != null)
      throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);
   input_stream = stream;
}

/** Constructor. */
public FLParserTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
static private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 9; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
static public void SwitchTo(int lexState)
{
   if (lexState >= 2 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

static protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   if (jjmatchedPos < 0)
   {
      if (image == null)
         curTokenImage = "";
      else
         curTokenImage = image.toString();
      beginLine = endLine = input_stream.getBeginLine();
      beginColumn = endColumn = input_stream.getBeginColumn();
   }
   else
   {
      String im = jjstrLiteralImages[jjmatchedKind];
      curTokenImage = (im == null) ? input_stream.GetImage() : im;
      beginLine = input_stream.getBeginLine();
      beginColumn = input_stream.getBeginColumn();
      endLine = input_stream.getEndLine();
      endColumn = input_stream.getEndColumn();
   }
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }
   image = jjimage;
   image.setLength(0);
   jjimageLen = 0;

   switch(curLexState)
   {
     case 0:
       try { input_stream.backup(0);
          while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
             curChar = input_stream.BeginToken();
       }
       catch (java.io.IOException e1) { continue EOFLoop; }
       jjmatchedKind = 0x7fffffff;
       jjmatchedPos = 0;
       curPos = jjMoveStringLiteralDfa0_0();
       break;
     case 1:
       jjmatchedKind = 74;
       jjmatchedPos = -1;
       curPos = 0;
       curPos = jjMoveStringLiteralDfa0_1();
       break;
   }
     if (jjmatchedKind != 0x7fffffff)
     {
        if (jjmatchedPos + 1 < curPos)
           input_stream.backup(curPos - jjmatchedPos - 1);
        if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
        {
           matchedToken = jjFillToken();
           TokenLexicalActions(matchedToken);
       if (jjnewLexState[jjmatchedKind] != -1)
         curLexState = jjnewLexState[jjmatchedKind];
           return matchedToken;
        }
        else
        {
         if (jjnewLexState[jjmatchedKind] != -1)
           curLexState = jjnewLexState[jjmatchedKind];
           continue EOFLoop;
        }
     }
     int error_line = input_stream.getEndLine();
     int error_column = input_stream.getEndColumn();
     String error_after = null;
     boolean EOFSeen = false;
     try { input_stream.readChar(); input_stream.backup(1); }
     catch (java.io.IOException e1) {
        EOFSeen = true;
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
        if (curChar == '\n' || curChar == '\r') {
           error_line++;
           error_column = 0;
        }
        else
           error_column++;
     }
     if (!EOFSeen) {
        input_stream.backup(1);
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
     }
     throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static int[] jjemptyLineNo = new int[2];
static int[] jjemptyColNo = new int[2];
static boolean[] jjbeenHere = new boolean[2];
static void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      case 73 :
         break;
      case 74 :
         if (jjmatchedPos == -1)
         {
            if (jjbeenHere[1] &&
                jjemptyLineNo[1] == input_stream.getBeginLine() &&
                jjemptyColNo[1] == input_stream.getBeginColumn())
               throw new TokenMgrError(("Error: Bailing out of infinite loop caused by repeated empty string matches at line " + input_stream.getBeginLine() + ", column " + input_stream.getBeginColumn() + "."), TokenMgrError.LOOP_DETECTED);
            jjemptyLineNo[1] = input_stream.getBeginLine();
            jjemptyColNo[1] = input_stream.getBeginColumn();
            jjbeenHere[1] = true;
         }
         break;
      default :
         break;
   }
}
static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

}
